/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author juanito
 */
public class Juanito extends javax.swing.JFrame {

    /**
     * Creates new form Juanito
     */
    public Juanito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("       Juanito");

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ramones-1.jpg"))); // NOI18N
        jMenuItem1.setText("New Projet...");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ramones-2.jpg"))); // NOI18N
        jMenuItem2.setText("New File...");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo.jpg"))); // NOI18N
        jMenuItem3.setText("Open Projet");
        jMenu1.add(jMenuItem3);

        jMenu13.setText("Open Recent Projet");
        jMenu13.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jMenu1.add(jMenu13);

        jMenuItem4.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jMenuItem4.setText("Close \"Air Tex_New\"");
        jMenu1.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jMenuItem5.setText("Open File......");
        jMenu1.add(jMenuItem5);
        jMenu1.add(jSeparator1);

        jMenu14.setText("Set Main Project");
        jMenu14.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jMenu1.add(jMenu14);

        jMenuItem6.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jMenuItem6.setText("\"AirText_New\" Propities");
        jMenu1.add(jMenuItem6);
        jMenu1.add(jSeparator2);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jMenuItem7.setText("Save");
        jMenuItem7.setEnabled(false);
        jMenu1.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Atletico-1.png"))); // NOI18N
        jMenuItem8.setText("Save All");
        jMenuItem8.setEnabled(false);
        jMenu1.add(jMenuItem8);

        jMenuItem9.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jMenuItem9.setText("Refresh All Files");
        jMenu1.add(jMenuItem9);

        jSeparator3.setForeground(java.awt.Color.red);
        jSeparator3.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jSeparator3.setOpaque(true);
        jMenu1.add(jSeparator3);

        jMenuItem10.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jMenuItem10.setText("Page Setup....");
        jMenu1.add(jMenuItem10);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jMenuItem11.setText("Print...");
        jMenuItem11.setEnabled(false);
        jMenu1.add(jMenuItem11);

        jMenuItem12.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jMenuItem12.setText("Print to HTLM...");
        jMenuItem12.setEnabled(false);
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jSeparator4.setBackground(java.awt.Color.red);
        jSeparator4.setForeground(java.awt.Color.red);
        jSeparator4.setFont(new java.awt.Font("Laksaman", 1, 18)); // NOI18N
        jSeparator4.setOpaque(true);
        jMenu1.add(jSeparator4);

        jMenuItem13.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jMenuItem13.setText("Exit");
        jMenu1.add(jMenuItem13);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenu3.setText("View");
        jMenu3.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Navigate");
        jMenu4.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Source");
        jMenu5.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Refactor");
        jMenu6.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Build");
        jMenu7.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jMenuBar1.add(jMenu7);

        jMenu8.setText("Run");
        jMenu8.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jMenuBar1.add(jMenu8);

        jMenu9.setText("CVS");
        jMenu9.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jMenuBar1.add(jMenu9);

        jMenu10.setText("Tools");
        jMenu10.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jMenuBar1.add(jMenu10);

        jMenu11.setText("Windows");
        jMenu11.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jMenuBar1.add(jMenu11);

        jMenu12.setText("Help");
        jMenu12.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jMenuBar1.add(jMenu12);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 697, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juanito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juanito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juanito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juanito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juanito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
